### ISSUE TITLE
Genespace docker

### ISSUE THREAD

**Issue by sanyalab** [jtlovell/GENESPACE#100]
Hello,

Can a dockerfile be created for Genespace and all its dependencies? That way it can run out-of-box

-Abhijit

**Comment by James-S-Santangelo** [comment]
I've recently created a `Singularity` container for `GENESPACE`, which is hosted [here](https://cloud.sylabs.io/library/james-s-santangelo/genespace/genespace). The source code (i.e., recipe file) can be found [here](https://github.com/James-S-Santangelo/singularity-recipes/tree/master/genespace). 

I tested the container on the test data and a separate dataset, and both runs finished without errors. The container is compatible with `singularity`/`apptainer`, but should also be cross-compatible with `Docker`. 

Hope this helps!

James

**Comment by sanyalab** [comment]
Hi James,

Thank you for the reply. I tried the following but get an error

`singularity pull library://james-s-santangelo/genespace/genespace`
`FATAL:   While pulling library image: error fetching image: image does not exist in the library: james-s-santangelo/genespace/genespace:latest (amd64)`

Is the architecture creating an issue?

Thanks
Abhijit

**Comment by sanyalab** [comment]
Ok... so I was able to download using the following command

`singularity pull --arch amd64 library://james-s-santangelo/genespace/genespace:1.2.3`

It gave some warnings but the SIF file is downloaded. I don't know how to execute this file.

`singularity exec genespace.sif` does not work as I do not know what the second argument should be.

Thanks
Abhijit

**Comment by James-S-Santangelo** [comment]
Hey Abhijit,

The easiest approach would be to put all of your `GENESPACE` code into an Rscript and then execute the script using the `singularity` container. A few points:

1. `GENESPACE` requires that you set the path to `MCScan-X` in your script. When using the container, this should be set to `/opt/MCScanX-master`. 
2. You need to bind whatever filesystem paths the container needs access to at runtime so that it can read/write to your machine. You only need to bind the root of the path. So, for example, if you were working somewhere in `/scratch/sanyalab/...`, you would need to bind the `/scratch` directory to the container. 

At the end, the command should look something like:

`singularity exec --bind /scratch genespace.sif Rscript myscript.R`

(Assuming you're working in `/scratch` and your script is called `myscript.R`).

Hope this helps!

James

**Comment by jtlovell** [comment]
Awesome. Thanks for working on this, guys.

**Comment by James-S-Santangelo** [comment]
Hey Abhijit,

Yes, that command should do the trick, though you may need to add `--bind <path/on/filesystem>` to make sure the container has access to any necessary filesystem directories where read/write operations will be performed by your script. 

Hope this helps!
James

**Comment by sanyalab** [comment]
Awesome!!! Thank you for the quick response.

-Abhijit
