### ISSUE TITLE
Why is it so hard to use GENESPACE?

### ISSUE THREAD

**Issue by GurjotSinghSidhu** [jtlovell/GENESPACE#158]
I started bioinformatics like two years ago and I have seen many programs which can be difficult to get started on. But GENESPACE is worse, I have spent a full week on this, trying so many different things but I can't even get the dependencies in right order. Whey people who design these programs don't think that these might be used by people who are just starting? Why not provide a good and detailed documentation? Thanks.

**Comment by jtlovell** [comment]
So, what exactly is wrong with the readme and three detailed tutorials that give step by step instructions on how to install and use the software? 
Once you work out the issues on your end, I'd very much welcome a contributed tutorial on how you got around your difficulties so that others do not run into the same issues.

**Comment by kenji-yt** [comment]
Hi @GurjotSinghSidhu @jtlovell I made a snakemake workflow which hopefully makes it easier to use GENESPACE. Here it is: https://github.com/kenji-yt/snake-GENESPACE :)
