### ISSUE TITLE
inversion breakpoint identification

### ISSUE THREAD

**Issue by Chenglin20170390** [jtlovell/GENESPACE#25]
Dear John,

 Many thanks for developing such useful tools.

 I saw the inversion from the output of genescape, like attached file. We would like to know the breakpint of inversion between reference and querys. The syntenicBlocks.txt.gz looks like what we want, can you talk more about the output of syntenicBlocks.txt.gz?  and do you have any suggestion for pick up the breakpoint of inversion from genespace?

   Thanks in advance.
<img width="344" alt="inversion" src="https://user-images.githubusercontent.com/33062118/186218864-466ba1b5-1730-48f6-8942-962795a4d9b1.png">

Best,
Lin

**Comment by jtlovell** [comment]
You can find inversions in the syntenicBlocks.txt.gz file: any row where orient == "-" is inverted. That file is mostly used internally by GENESPACE, but it does give the coordinates of the blocks. You can use those to parse a gff to get all the genes in an interval. Does this help?

I'll add this to my to do list for the next update: 
#### add query function to pull syntenic blocks by a set of rules, including inversions

**Comment by Chenglin20170390** [comment]
Thank you. I'm looking forward to the next version

**Comment by Chenglin20170390** [comment]
Hi  John,  I have a question about syn region in multiple genome alignments by genespace.

As you can see，I keep the **only  inversion block coordinates (** ref:genome 1 and genome 2) from syntenicBlocks.txt.gz, and visilization via regs function in GENESPACE. 

1) why the frist syn region between genome 1 and 2 not like inversions (show in blue arrow)?

2) I am interesting in the derived inversion regions ,that mean I want to know for genome 3 or 4 ,5 , some regions may came from genome 1 , and others from genome2.   So, first I compaed genome 1 and 2 to find inversion regions, but how can I find coordinates regions of genome 3,4 and5 ? based on the genome 1 or genome 2? Does there have any function to quick pick up the syn region based on one genome ?

3) As I used reference genome 1 inversion position to show the regions of interest (yellow circle), why genome 3 and genome 4 have a large syn block  which is not show  between genome 1 and genome 2 ?

<img width="640" alt="image" src="https://user-images.githubusercontent.com/33062118/187877311-fe3cd6dc-2d7f-4650-9321-2580413ef9a5.png">


Thanks

**Comment by jtlovell** [comment]
So, you specified a bunch of regions that are inverted between two genomes and are tracking these across multiple genomes. Correct? Are you sure that all of those regions themselves are inverted? I would do dotplots of each genome1-genome2 region you are looking at and see if perhaps there is a nested non-inverted sequence in a larger inversion that you are plotting. 

In terms of that retained region, its hard to know what is up there. It is possible that the block you are showing is a partially syntenic region that is broken up in that particular contrast. This type of thing happens with `plot_riparian` due to the messiness of synteny across multiple genomes. It happens less in `plot_riparianHits`. 

Regardless, `plot_riparian` is not very good at making these types of plots where the blocks are subdivided across many genomes. I would make individual plots for each block (e.g. looping for each region) and seeing what going on. In the next release, the function will work on pre-calculated coordinates (and nothing else), which will allow better manual specification and manipulation like this.

**Comment by Chenglin20170390** [comment]
Yes,  I specified a bunch of regions that are inverted from **syntenicBlocks.txt.gz file: any row where orient == "-"** between two genomes and are tracking these across multiple genomes. 
   
  Thanks,  I'm looking forward to the next version of GENESPACE.

**Comment by Saurav0731** [comment]
Hi,

I am using GENESPACE v1.3.1 for my project and I am interested in identifying inversion breakpoints. In a previous comment, it was mentioned that inversions can be found in the `syntenicBlocks.txt.gz` file, where rows with orient == "-" indicate inverted blocks. However, when I checked my results, I did not see an orient column in that file.

Instead, I found two files in the results directory;  `syntenicBlock_coordinates.csv` and `syntenicRegion_coordinates.csv` . Both of these include an orient column and seem to contain the coordinates I would need to extract inversions.

Could you clarify:

1. Which of these files is the appropriate one to use for detecting inversions (syntenicBlock_coordinates.csv vs syntenicRegion_coordinates.csv)?
2.  How do these two files differ in terms of what they represent?
3. Is there any documentation available that explains the meaning of each column in these files?

Thank you for your help!
