### ISSUE TITLE
usage of outgroup

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#37]
Hi John,

I am not sure about the usage of `outgroup` and would like to know if I understand this correctly.

Take a three-specie phylogeny `(A(B,C))` as an example, and there was a WGD in the most recent ancestor of B and C. We expect to see a `1:2:2` relationship in the orthologs identified by Orthofinder. With or without `outgroup=A`, we would expect to see a `2:2` syntenic relationship for B-C in both cases if `ploid=(1,2,2)`. So `outgroup` makes no difference here. But if we exclude A from the beginning (OrthoFinder), we will get either a `2:2` syntenic relationship with `ploid=(2,2)`, or `1:1` syntenic relationship with `ploid=(1,1)`.

Best wishes,

Tao

**Comment by jtlovell** [comment]
Hi Tao, 
I guess `outgroup` is a bit of a misnomer ... I might need to reconsider this label for the next release. 
The outgroup is any genome that you want to use for the orthofinder run, but not for synteny (etc.). It has nothing to do with the phylogenetic position of the genomes, although it typically is the outgroup in your phylogeny (A in your example). See the "considerations" methods section of the GENESPACE paper for more details. 
The example you bring up here is a perfect one. There is a WGD on the branch connecting A to B|C. If orthofinder is run without genome A, homeologs between B and C would likely not be in the same orthogroups, since each would have a MRCA in the ancestral genome to both B and C. However, if you include A in OrthoFinder, the MRCA of all three genomes would likely have five copies in the extant genomes (2 in each of B and C). 
So, in terms of specifying ploidy you want to take the product of all WGDs in the phylogeny. For just (B,C), `ploidy = c(1,1)`.  For (A(B,C), `ploidy = c(1,2,2)`. You would set `outgroup = "A"` if you wanted to study differences between B|C homeologs, but were not interested in A-->B or A-->C synteny. 
Does this make sense?
John

**Comment by xiaoyezao** [comment]
Thank you for the detailed explanation. It is clear to me now. 

Changing `outgroup` label makes sense. To a phylogenetics/evolution biology scientist, "outgroup" is A in (A(B,C)) but not B or C.
