### ISSUE TITLE
non-syntenic chromosomes in the plot

### ISSUE THREAD

**Issue by aberaslop** [jtlovell/GENESPACE#43]
Hi!
A pleasure to use GENESPACE, as always. 
I was wondering if there is any way to have non-syntenic chromosomes still depicted on the plot. I have a set of 6 genomes with different numbers of chromosomes, and when making the plot, those not sharing genes, are not shown. 
Thanks!!
L.

**Comment by jtlovell** [comment]
I'n not sure I'm following ... are you missing the segments of those chromosomes in your riparian plot? Maybe post an image of the issue?

**Comment by aberaslop** [comment]
Hi John,

Sorry, I was not very clear. I realized that some contigs (not all of my fragments are full chromosomes) in some genomes were missing from the plot. Further inspection revealed that those missing fragments were always short-ish (shorter than 200,000bp), and had few genes (as reported in the gff). Looking up information about another issue, I found part of the solution here #24. Decreasing minGenes2plot makes some of those fragments appear in the plot.  I consider this to be the answer, so I think we can close the issue. Thank you!

**Comment by AnthonyPiot91** [comment]
Hi,

I reopen this issue because I am curious to know if it possible to plot chromosomes with no syntenic regions in the riparian plot.

I am looking to display the synteny in bacteria genomes which include many plasmids. The problem is that some of these plasmids have no syntenic regions with other plasmids. 

Is there of way to plot these plasmids with GENESPACE nonetheless, or a possibility for me to tweak the code to do so?

Thanks,
Anthony
