### ISSUE TITLE
Error in flagging synteny for each pair of genomes

### ISSUE THREAD

**Issue by austintdaigle** [jtlovell/GENESPACE#48]
I was really excited to discover this program, and had some initial success testing it out on pairs of drosophila species. However, I have run into an issue when scaling it up to a larger set of species. I am running the latest version (1.0.3). 

Steps to reproduce.
- Download all 37 refseq drosophila genomes from NCBI
- Run GENESPACE with default settings and NCBI preset for parsing

The program seems to run successfully for steps 1-3 (I can provide output messages and data if needed). 

On step 4, I get the error:

``` 
4. Flagging synteny for each pair of genomes ...
#chunks 1-8 ran successfully, cutting them out for space (this means 8*16=128 ran successfully)
	# Chunk 9 / 47 (12:35:03 AM) ... 
Error in rbindlist(mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { : 
  Item 9 of input is not a data.frame, data.table or list
Calls: run_genespace -> synteny -> rbindlist -> lapply -> FUN -> rbindlist
In addition: Warning message:
In mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  scheduled cores 10, 9, 12, 11, 13, 14, 15, 16 encountered errors in user code, all values of the jobs will be affected
Execution halted
```

I thought this may be an error related to the number of cores, so I switched to nCores =1. The program failed in a similar way, stopping after flagging synteny for ~130 pairs. 

With one core:

```
Error in x$dist[[i]] : subscript out of bounds
Calls: run_genespace ... dbscan -> frNN -> sort.frNN -> lapply -> FUN -> order
Execution halted
```

So I think the 129th comparison is failing somehow, but I am unsure how to debug this further. I would appreciate any help you could provide.

**Comment by austintdaigle** [comment]
It did not unfortunately. I sent you an email!

**Comment by jtlovell** [comment]
OK - thanks Austin. There were a lot of complexities with these data that V1 was not ready for. Thanks for sharing. An outline of what the issues were and how they are now addressed (pushed updates to /dev)

1. Some gene names had `:` in them. The parser written for the orthofinder geneID dictionary used `:` as the delimiter. I have changed this to `: ` (colon followed by a space) and added a catch in the genome QCing step in `init_genespace` to error out if any geneID has `: ` in it. 
2. The NCBI seqID (first gff3 column) dictionary exists in any row with the type (3rd gff3 column) == "region". Apparently some genomes (I'm looking at you D. elegans) don't supply this dictionary at all and just give "unknown" as the chr ID. For example, line 1 of D. elegans gene.gff3: `NW_024545461.1 RefSeq region 1 1272051 . + . ID=NW_024545461.1:1..1272051;Dbxref=taxon:30023;Name=Unknown;chromosome=Unknown`. This caused the entire genome to be put into a chromosomeID of 'unknown', which totally messed up estimates of synteny, in part because gene order was inferred within chromosomes (which is now across chromosomes). This is now fixed where any time chromosome = Unknown, the chromosome is not re-named.
