### ISSUE TITLE
ploidy question

### ISSUE THREAD

**Issue by dabitz** [jtlovell/GENESPACE#67]
Hi John,

How do you define the ploidy parameter when running species with different ploidy levels, i.e. 1x, 2x, 4x?

Thanks
André here

**Comment by jtlovell** [comment]
Sup brah, 
Do you mean functionally in genespace or more philosophically 'what does ploidy mean and why am I here?'. If the former, you supply `init_genespace(..., genomeIDs = c("g1", "g2", "g3"), ploidy = c(1,2,4), ...)`. If the latter, you might seek your favorite guru or check the paralogs section of the genespace manuscript methods. In short, ploidy should be specified in concert with the phylogenetic context of your run. For example, a run with only two Maize genomes should set ploidy to `c(1, 1)`, even though maize is a tetraploid, because the species in the run do not encapsulate the WGD. Alternatively, if you included rice in the run, which diverged prior to the WGD, then both maize genomes would have ploidy = 2. 
Hope this helps, 
John

**Comment by dabitz** [comment]
Great! You got my point!
