### ISSUE TITLE
Error: In max(hcBlk$rnd1) : no non-missing arguments to max; returning -Inf

### ISSUE THREAD

**Issue by timregan** [jtlovell/GENESPACE#68]
Hi, I have a recurring issue with one of my GENESPACE results using the dev version.
Hopefully you can let me know what the error means (I have been unable to find a solution searching other issues or from the code). 
It fails at the point of running the dotplot (step 4):

GENESPACE v1.0.8 (pre-release): synteny and orthology constrained comparative genomics

Checking Working Directory ... PASS: `tregan/Genespace_dev`
Checking user-defined parameters ...
	Genome IDs & ploidy ... 
		SpeciesA: 1
		SpeciesB : 1
		SpeciesC  : 1
		SpeciesD    : 1
	Outgroup ... NONE
	n. parallel processes ... 1
	collinear block size ... 1
	collinear block search radius ... 10
	n gaps in collinear block ... 100
	synteny buffer size... 100
	only orthogroups hits as anchors ... TRUE
	n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
	SpeciesA: 36414 / 36414 geneIDs exactly match (PASS)
	SpeciesB : 34530 / 34530 geneIDs exactly match (PASS)
	SpeciesC  : 37478 / 37478 geneIDs exactly match (PASS)
	SpeciesD    : 45815 / 45815 geneIDs exactly match (PASS)
Checking dependencies ...
	Found valid path to OrthoFinder v2.54: `orthofinder`
	Found valid path to DIAMOND2 v2.015: `diamond`
	Found valid MCScanX_h executable: `tregan/MCScanX/MCScanX_h`

############################
1. Running orthofinder (or parsing existing results)
	Checking for existing orthofinder results ...
	... found existing run, not re-running orthofinder
        re-ordering genomeIDs by the species tree: SpeciesA,
                SpeciesC, SpeciesB, SpeciesD

############################
2. Annotated/concatenated bed file exists

############################
3. Annotated/blast files exists

############################
4. Flagging synteny for each pair of genomes ...
	...SpeciesD v. SpeciesB:      20870 hits (782 anchors) in 13 blocks (0 SVs)
	...SpeciesC v. SpeciesD:       41555 hits (4545 anchors) in 34 blocks (20 SVs)
	...SpeciesA v. SpeciesC:   16075 hits (1273 anchors) in 22 blocks (6 SVs)
	...SpeciesA v. SpeciesD:     4606 hits (400 anchors) in 12 blocks (1 SVs)
	...SpeciesC v. SpeciesB:    6357 hits (580 anchors) in 12 blocks (0 SVs)
	...SpeciesA v. SpeciesB:  59 hits (13 anchors) in 1 blocks (0 SVs)
	...SpeciesD v. SpeciesD:         71452 hits (45790 anchors) in 14 blocks (0 SVs)
	...SpeciesB v. SpeciesB:   46350 hits (34523 anchors) in 14 blocks (0 SVs)
	...SpeciesC v. SpeciesC:     70511 hits (37221 anchors) in 1841 blocks (0 SVs)
	...SpeciesA v. SpeciesA: 87585 hits (36195 anchors) in 139 blocks (0 SVs)

############################
Generating dotplots ...

Error in seq.default(from = 1000, to = max(hcBlk$rnd1), by = 1000) : 
  'to' must be a finite number
Calls: run_genespace ... continuous_scale -> check_breaks_labels -> seq -> seq.default
In addition: Warning message:
In max(hcBlk$rnd1) : no non-missing arguments to max; returning -Inf
Execution halted

**Comment by jtlovell** [comment]
Thanks for using the beta genespace release. This is a great catch and it will be an easy fix on my end (see below). 

The source of the problem: It looks like my error catch was too stringent ... two of your species have basically no synteny. 
`...SpeciesA v. SpeciesB: 59 hits (13 anchors) in 1 blocks (0 SVs)`. Are the species very diverged? It looks like all of the intergenomic searches give a huge reduction in the number of hits to anchors (10-fold or more). Some of the dotplots were probably generated before it errored out ... how do they look? My guess is there isn't much synteny. 

I set the lower bound at needing a hard floor of 50 hits (so AvB this just makes it), but then breaks the plotting routine, likely because the window for aggregating hits is also hard-coded and set for larger genomes.

Can you send me the input data for this run so I can ensure that troubleshooting worked right? If so, shoot me an email jlovell[at]hudsonalpha.org or DM me on twitter and I'll share a folder to transfer the files. 
Cheers,
John

**Comment by jtlovell** [comment]
The fix for plotting genomes with too few hits is written and will be released tomorrow with v1.1.3.

**Comment by jtlovell** [comment]
OK. The other problem, getting through the pipeline when some of the genomes have basically no synteny, should be resolved in v1.1.4, which was pushed to /dev just now. Let me know if this doesn't resolve the issue.
